### PR TITLE
Removed bad commit files

### PR DESCRIPTION
**Pull request by SFC-Sarge**
@madskristensen; I removed the files that was committed by mistake so that this is a clean pull request, to allow addition of the ToolWindows Toolbar and buttons to the custom-tool-windows.md file only.

### CODE REVIEW

**Comment by SFC-Sarge** [comment]
@madskristensen; some of the files from the first commit would not let me remove them (all of the json files) give me 404 error on clicking delete in Github. You only want the custom-tool-windows.md file.

**Comment by madskristensen** [comment]
Thanks. Let me know when this is ready to merge

**Comment by SFC-Sarge** [comment]
@madskristensen; It is ready but please only merge #22, It should only have the MD file.

**Comment by SFC-Sarge** [comment]
@madskristensen; My forked main and yours should look alike now except for the MD file changes. It is ready to merge when you are.

**Comment by SFC-Sarge** [comment]
@madskristensen  It would seem that some of my paid for VS Extensions (like TabStudio) create folders in the solution when the Doc's project was forked and then opened in VS.

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
